// <auto-generated />
namespace CompetencyManagement.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class D_Assignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(D_Assignment));
        
        string IMigrationMetadata.Id
        {
            get { return "202004230521441_D_Assignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
